# Continuous Integration Workflow
name: "CI Build"

on:
  pull_request:
    branches:
      - 9bit
  workflow_call:

env:
  RGBDS_VERSION: "v0.8.0"

jobs:
  build-ubuntu:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # SET ENVIRONMENT VARIABLES
      - id: set-env-var
        name: "Set environment variables"
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      # INSTALL DEPENDENCIES
      - id: apt-get-depends
        name: "Install build dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install bison gcc git make -y;
          
      # CHECKOUT RGBDS
      - id: checkout-rgbds
        name: "Checkout gbdev/rgbds"
        uses: actions/checkout@v3
        with:
          path: rgbds
          ref: ${{ env.RGBDS_VERSION }}
          repository: gbdev/rgbds
      
      # INSTALL RGBDS
      - id: install-rgbds
        name: "Install gbdev/rgbds"
        working-directory: rgbds
        run: |
          sudo make install
      
      # CHECKOUT REPOSITORY
      - id: checkout-polished9bitedit
        name: "Checkout OngoGablogian/polished9bitedit"
        uses: actions/checkout@v3
      
      # BUILD ROMS
      - id: build-polishedcrystal
        name: "Build polishedcrystal"
        run: |
          make -j$(nproc) vc
          mkdir build
          mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystaledit-3.0.0-beta-${{ env.SHORT_SHA }}.gbc
          make tidy

      # BUILD SAVE PATCH
      - id: build-polishedcrystal-bsp
        name: "Build polishedcrystal-savepatch"
        run: |
          make -j$(nproc) bsp
          mv polishedcrystal-3.0.0-beta.bsp build/polishedcrystaledit-savepatch-3.0.0-beta-${{ env.SHORT_SHA }}.bsp
          make tidy
          
      # UPLOAD ARTIFACTS
      - id: upload-polishedcrystal
        name: "Upload polishedcrystal artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "polishedcrystal"
          retention-days: 1
          path: |
            build/polishedcrystaledit-3.0.0-beta-${{ env.SHORT_SHA }}.*

      - id: upload-polishedcrystal-savepatch
        name: "Upload polishedcrystal savepatch"
        uses: actions/upload-artifact@v3
        with:
          name: "polishedcrystal-savepatch"
          retention-days: 1
          path: |
            build/polishedcrystaledit-savepatch-3.0.0-beta-${{ env.SHORT_SHA }}.*
